import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Oversized Cotton Shirt",
    brand: "Violet Essentials",
    price: 499,
    category: "Tops",
    image: "https://picsum.photos/seed/fashion1/800/1000",
    isNew: true
  },
  {
    id: 2,
    name: "Slim Fit Chinos",
    brand: "H&M",
    price: 349,
    originalPrice: 499,
    category: "Pants",
    image: "https://picsum.photos/seed/fashion2/800/1000",
    isSale: true
  },
  {
    id: 3,
    name: "Ribbed Knit Dress",
    brand: "Violet Essentials",
    price: 699,
    category: "Dresses",
    image: "https://picsum.photos/seed/fashion3/800/1000",
  },
  {
    id: 4,
    name: "Classic Denim Jacket",
    brand: "Levi's",
    price: 1299,
    category: "Jackets",
    image: "https://picsum.photos/seed/fashion4/800/1000",
  },
  {
    id: 5,
    name: "Basic White Tee",
    brand: "H&M",
    price: 149,
    category: "Tops",
    image: "https://picsum.photos/seed/fashion5/800/1000",
  },
  {
    id: 6,
    name: "High Waist Cargo Pants",
    brand: "Violet Essentials",
    price: 799,
    category: "Pants",
    image: "https://picsum.photos/seed/fashion6/800/1000",
    isNew: true
  },
  {
    id: 7,
    name: "Floral Summer Dress",
    brand: "H&M",
    price: 549,
    category: "Dresses",
    image: "https://picsum.photos/seed/fashion7/800/1000",
  },
  {
    id: 8,
    name: "Leather Biker Jacket",
    brand: "Mango",
    price: 2499,
    category: "Jackets",
    image: "https://picsum.photos/seed/fashion8/800/1000",
  },
  {
    id: 9,
    name: "Striped Linen Shirt",
    brand: "Violet Essentials",
    price: 599,
    category: "Tops",
    image: "https://picsum.photos/seed/fashion9/800/1000",
  },
  {
    id: 10,
    name: "Pleated Midi Skirt",
    brand: "H&M",
    price: 649,
    category: "Bottoms",
    image: "https://picsum.photos/seed/fashion10/800/1000",
    isSale: true,
    originalPrice: 899
  },
  {
    id: 11,
    name: "Chunky Knit Sweater",
    brand: "Zara",
    price: 899,
    category: "Tops",
    image: "https://picsum.photos/seed/fashion11/800/1000",
  },
  {
    id: 12,
    name: "Wide Leg Trousers",
    brand: "Violet Essentials",
    price: 749,
    category: "Pants",
    image: "https://picsum.photos/seed/fashion12/800/1000",
  },
  {
    id: 13,
    name: "Satin Slip Dress",
    brand: "H&M",
    price: 599,
    category: "Dresses",
    image: "https://picsum.photos/seed/fashion13/800/1000",
  },
  {
    id: 14,
    name: "Puffer Jacket",
    brand: "North Face",
    price: 3299,
    category: "Jackets",
    image: "https://picsum.photos/seed/fashion14/800/1000",
  },
  {
    id: 15,
    name: "Graphic Print Hoodie",
    brand: "Cotton On",
    price: 499,
    category: "Tops",
    image: "https://picsum.photos/seed/fashion15/800/1000",
  },
  {
    id: 16,
    name: "Formal Blazer",
    brand: "Violet Essentials",
    price: 1199,
    category: "Jackets",
    image: "https://picsum.photos/seed/fashion16/800/1000",
  },
];

export const CATEGORIES = ["Tops", "Pants", "Dresses", "Jackets", "Bottoms"];